[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "InconsolataGo Nerd Font"
style = "Bold"

[font.bold_italic]
family = "InconsolataGo Nerd Font"
style = "Bold"

[font.italic]
family = "InconsolataGo Nerd Font"
style = "Bold"

[font.normal]
family = "InconsolataGo Nerd Font"
style = "Bold"

[window]
opacity = 0.65
blur = true
decorations = "Full"
padding = { x = 4, y = 4 }
dynamic_padding = true
